title: "Benjamin Pampel"
baseURL: "https://bpampel.de"
languageCode: "en-us"
theme: "pulp"
canonifyURLs: true
uglyurls: true
sectionPagesMenu: "main"

params:
  Author: "Benjamin Pampel"
  publicationYear: 2022
  description: ""
  avatar: "me.png"
  avatarDescription: "me"
  favicon: "favicon.ico"

outputs:
  section: ["JSON", "HTML"]
  term: ["JSON", "HTML"]

menu:
  main:
  - identifier: About
    name: About
    pre: <i class='fa fa-question'></i>
    url: /about.html
  - identifier: github
    name: GitHub
    pre: <i class='fab fa-github'></i>
    url: https://github.com/bpampel/
  - identifier: Kuchenwiki
    name: Kuchenwiki
    pre: <i class='fa fa-birthday-cake'></i>
    url: /kuchenwiki
  - identifier: Zettel
    name: Zettelkasten
    pre: <i class='fa fa-sticky-note'></i>
    url: /zettel
