title: "Benjamin Pampel"
baseURL: "https://bpampel.github.io"
languageCode: "en-us"
theme: "pulp"
canonifyURLs: true
uglyurls: true
sectionPagesMenu: "main"

params:
  Author: "Benjamin Pampel"
  publicationYear: 2022
  description: ""
  avatar: "baerli.jpg"
  avatarDescription: "me"
  favicon: "favicon.ico"

outputs:
  section: ["JSON", "HTML"]
  term: ["JSON", "HTML"]
