title: "Benjamin Pampel"
baseURL: "https://bpampel.de"
languageCode: "en-us"
theme: "pulp"
canonifyURLs: true
uglyurls: true
sectionPagesMenu: "main"

params:
  Author: "Benjamin Pampel"
  publicationYear: 2022
  description: "
I'm a physicist currently working as doctoral researcher at the [MPI-P](https://www.mpip-mainz.mpg.de/) in Mainz.

My research focuses on developing new computational methods to better understand soft matter phenomena.

The first part of my PhD research has now been submitted for publication and is up on [arXiv](https://arxiv.org/abs/2202.13459)!
    "
  avatar: "me.png"
  avatarDescription: "me"
  favicon: "favicon.ico"

outputs:
  section: ["JSON", "HTML"]
  term: ["JSON", "HTML"]

menu:
  main:
  - identifier: Kuchenwiki
    name: Kuchenwiki
    pre: <i class='fa fa-birthday-cake'></i>
    url: /kuchenwiki
  - identifier: Zettel
    name: Zettelkasten
    pre: <i class='fa fa-sticky-note'></i>
    url: /zettel
